### ISSUE TITLE
Homebridge Testing & Errors (plugin mostly working)

### ISSUE THREAD

**Issue by suburbanidiot** [KyleBoyer/homebridge-blaq#1]
**Describe Your Problem:**
Testing this integration out. I have 2 blaQs both on an IOT VLAN with reasonable, but restrict rules.  The Homebridge server is on another VLAN and can talk to other devices in the IOT network on multiple ports.  Testing process below:

Scenario 1. Installed plugin - manually added blaQ IPs & rebooted.  (Log errors below)
Scenario 2. Uninstalled & reinstalled plugin with no manual devices setup / reboot (with same log errors)
Scenario 3. After another reboot, I setup one device at a time manually.  No Errors.  Initially...
* **Scenario 3 - A: single entry error after manual adding a single device / reboot
* **Scenario 3 - B: No error after reboot, but random misbehavior while operating (one blaQ stopped responding to a command at *12:32:40") that was fixed by a BlaQ device re-sync/reboot

**Potential Bug:** duplicate entries for each garage door show in both homebridge accessories & in homekit
* 2 named blaQ "device-id" - these accessories do not do anything as far as I can tell
* 2 named with manually given "display name"

**Logs:** 

**Scenario 1:** Errors repeating over & over again
[7/15/2024, 11:53:58 AM] [Homebridge BlaQl Reinitializing EventSource...
[7/15/2024, 11:53:58 AM] [Homebridge Blall EventSource got error Event { type:
'error', message: 'getaddrinfo ENOTFOUND undefined' }

**Scenario 2:**
[7/15/2024, 12:15:14 PM] [Homebridge BlaQ] Reinitializing EventSource...
[7/15/2024, 12:15:14 PM] [Homebridge BlaQ] EventSource got error Event { type: 'error', message: 'getaddrinfo ENOTFOUND undefined' }
[7/15/2024, 12:15:14 PM] [Homebridge BlaQ] Reinitializing EventSource...

**Scenario 3:**
* **A:**
[7/15/2024, 12:16:43 PM] [Homebridge BlaQ] EventSource got error Event {
  type: 'error',
  message: 'Parse Error: Invalid character in chunk size'
}
* ** B:**
[7/15/2024, 12:16:43 PM] [Homebridge BlaQ] Reinitializing EventSource...
[7/15/2024, 12:32:40 PM] [Homebridge BlaQ] EventSource got error Event {
  type: 'error',
  message: 'Parse Error: Invalid character in chunk size'
}
[7/15/2024, 12:32:40 PM] [Homebridge BlaQ] Reinitializing EventSource...
[7/15/2024, 12:32:50 PM] [Homebridge BlaQ] EventSource got error Event { type: 'error', message: 'read ECONNRESET' }
[7/15/2024, 12:32:50 PM] [Homebridge BlaQ] Reinitializing EventSource...
[7/15/2024, 12:48:33 PM] [Homebridge BlaQ] EventSource got error Event {
  type: 'error',
  message: 'Parse Error: Invalid character in chunk size'
}
[7/15/2024, 12:48:33 PM] [Homebridge BlaQ] Reinitializing EventSource...
[7/15/2024, 12:48:43 PM] [Homebridge BlaQ] EventSource got error Event { type: 'error', message: 'read ECONNRESET' }
[7/15/2024, 12:48:43 PM] [Homebridge BlaQ] Reinitializing EventSource...

**Plugin Config:**

```json
{
    "name": "Homebridge BlaQ",
    "devices": [
        {
            "displayName": "Left Garage Door",
            "host": "192.168.4.106",
            "port": 80
        },
        {
            "displayName": "Right Garage Door",
            "host": "192.168.4.31",
            "port": 80
        }
    ],
    "enableSeparateObstructionSensor": true,
    "enableMotionSensor": true,
    "enablePreCloseWarning": true,
    "enableLockRemotes": false,
    "enableLight": true,
    "enableLearnMode": false,
    "platform": "BlaQHomebridgePlugin"
}
```

**Environment:**
* **Plugin Version**: v0.2.16
* **Homebridge Version**: v1.8.3
* **Node.js Version**: v18.19.0
* **NPM Version**": 10.2.3
* **Operating System**: Debian GNU/Linux Bookworm (12)

**Comment by KyleBoyer** [comment]
Hmm, for scenario one, the error seems to indicate that it was trying to use an undefined host/ip to connect to - very strange. I'll be digging into the code to see how that could be possible. Only thing that comes to mind is if the config.json actually omitted that value, but I do have another theory to look into as well.

For scenario two, it appears to be the same issue - this could be because homebridge cached the saved accessory. In the Homebridge UI, you can go to settings -> remove single accessory and then delete all the entries mentioning blaq. Then restart the plugin and see if this removes those errors. If you do these steps and the error still occurs, I'm inclined to believe it would be an mDNS/Bonjour discovery issue, where the IP address isnt getting returned. If possible, can you review the plugin logs for "Discovered device via" to see if its loading devices via the config or via mDNS discovery?

For scenario three, do you have any other proxies or any other configs that might be changing the HTTP version / headers? I have not seen that error before. A quick google search takes me to this: https://github.com/nodejs/node/issues/47528 However, if the device was misbehaving and this error was transient, then that is a good sign. One thing I might recommend is to make sure your GDO BlaQ devices are running the latest ESPHome firmware.

**Comment by suburbanidiot** [comment]
Thanks for the quick followup!  I will have to replicate all scenarios again as I already removed the plugin & deivces...  I'm going to put them into the VLAN where the homebridge server lives.  My guess it is mDNS not making the hop between my VLAN allow/block rules.  I also noticed I somehow disabled IGMP (so it might be my network as well).

No proxies & both blaQs are running 2024.6.0b5.

**Comment by KyleBoyer** [comment]
I notice mine are on 2024.6.6, so that might be worth trying, especially on a beta version(guessing that's the b in your version number).

**Comment by suburbanidiot** [comment]
Thanks!  Will do!

**Comment by suburbanidiot** [comment]
I upgraded it to 2024.6.6.  It might be too soon to call for victory, but it looks like that might be the fix!  I put them back on the IOT network (as I had same behavior on the server network prior to firmware update).  All the weird device log errors are gone.

I didn't mention this before, but I still have the blue flashing light, but that looks like that might because I have my HA instance off.

The logs report the wifi signal now so I bet it is their way of a keep alive?  Felt like it was a timeout issue before, but I'm only guessing.  BEST OF ALL: no HA.  Homebridge is rocking the integration.  Can’t believe it was the firmware this whole time.

FYI: I had to change your integration to a child bridge & stop it manually before I could fully remove the cached "blaq" accessories.  If I didn't it would continue to readd it after deletion.  While stopped, I updated the JSON with "Left & RIght Doors" & all is right with the world.

Thanks again for the help & thank you for writing this intgration.  As you can tell I much prefer homebridge over HA.  Way less overhead.

**Comment by KyleBoyer** [comment]
That is awesome news! I also am a fan of just HomeBridge and didn't like the stray HA just for a select device. Please feel free to close this issue when you're sure that's the fix, otherwise I'll close it after it's inactive for a period of time. Thanks for filling me in!

**Comment by suburbanidiot** [comment]
Closed & fixed!  Always update your firmware.  Even if the vendor says it's fine. ;-)
