### ISSUE TITLE
Random open / close reporting in Home Kit

### ISSUE THREAD

**Issue by JohnRucker** [KyleBoyer/homebridge-blaq#3]
**Describe Your Problem:**
I just installed this plugin yesterday and it is working but I get random reports in Home Kit that my door is opening and closing.  Here are three examples around the time it happened.  The log file shows "EventSource got error Event" and appears to Reboot.  Is there something I can do to my configuration to help this?  Not sure what is causing it.

**Logs:**
**12:24 bogus open / close**
```
[01/08/2024, 12:24:50] [Homebridge BlaQ] [Guest] GDO blaQ log: [D][sensor:094]: 'Heap Free': Sending state 245492.00000 B with 0 decimals of accuracy
[01/08/2024, 12:24:50] [Homebridge BlaQ] [Guest] Processing state event: {"id":"sensor-heap_free","value":245492,"state":"245492 B"}
[01/08/2024, 12:25:03] [Homebridge BlaQ] EventSource got error Event { type: 'error', message: 'read ECONNRESET' }
[01/08/2024, 12:25:03] [Homebridge BlaQ] Reinitializing EventSource...
```

**12:09 bogus open / close**
```
[01/08/2024, 12:09:43] [Homebridge BlaQ] [Guest] GDO blaQ log: [D][sensor:094]: 'Heap Free': Sending state 245508.00000 B with 0 decimals of accuracy
[01/08/2024, 12:09:43] [Homebridge BlaQ] [Guest] Processing state event: {"id":"sensor-heap_free","value":245508,"state":"245508 B"}
[01/08/2024, 12:09:55] [Homebridge BlaQ] EventSource got error Event { type: 'error', message: 'read ECONNRESET' }
[01/08/2024, 12:09:55] [Homebridge BlaQ] Reinitializing EventSource...
[01/08/2024, 12:09:55] [Homebridge BlaQ] [Guest] GDO blaQ log: [C][version.text_sensor:021]: Version Text Sensor 'ESPHome Version'
```

**11:54 bogus open / close**
```
[01/08/2024, 11:54:39] [Homebridge BlaQ] [Guest] GDO blaQ log: [D][sensor:094]: 'Heap Free': Sending state 245488.00000 B with 0 decimals of accuracy
[01/08/2024, 11:54:39] [Homebridge BlaQ] [Guest] Processing state event: {"id":"sensor-heap_free","value":245488,"state":"245488 B"}
[01/08/2024, 11:54:48] [Homebridge BlaQ] EventSource got error Event { type: 'error', message: 'read ECONNRESET' }
[01/08/2024, 11:54:48] [Homebridge BlaQ] Reinitializing EventSource...
[01/08/2024, 11:54:48] [Homebridge BlaQ] [Guest] GDO blaQ log: [C][version.text_sensor:021]: Version Text Sensor 'ESPHome Version'
```

**Plugin Config:**

```json
{
    "name": "Homebridge BlaQ",
    "devices": [
        {
            "displayName": "Guest",
            "host": "10.50.0.32",
            "port": 80,
            "mac": "34:B7:DA:61:30:74"
        }
    ],
    "garageDoorType": "garage",
    "enableSeparateObstructionSensor": false,
    "enableMotionSensor": false,
    "enablePreCloseWarning": false,
    "enableLockRemotes": false,
    "enableLight": true,
    "enableLearnMode": false,
    "platform": "BlaQHomebridgePlugin"
}
```

**Screenshots:**

<img width="506" alt="image" src="https://github.com/user-attachments/assets/288afb6d-6335-4021-8aef-3b3c75695697">

**Environment:**

ESPHome Version of BlaQ: 2024.7.0
Plugin Version: 0.2.25
Homebridge Version: 1.8.4 -V
Node.js Version: v20.16.0
Operating System: Raspbian GNU/Linux Bullseye (11)

**Comment by KyleBoyer** [comment]
Are all those bogus events approx 15min apart each time? Im wondering if you have any proxies or things in the middle that might be configured with this as a timeout. Or possibly the keep alive NodeJS or tcp OS settings.

**Comment by JohnRucker** [comment]
Everything is on the same 10.x.x.x private subnet, no routers or proxies between the homebridge gateway and the BlaQ.  No they don't seem to be occurring at any repeatable interval.  Sometimes there is a good hour between them and others 10 minutes.  It may get worse the longer it is on.

**Comment by KyleBoyer** [comment]
Hmm okay I'll try to reproduce this issue with the open/close events, but as long as the event source successfully reconnects, the ECONNRESET shouldn't be an issue.

**Comment by JohnRucker** [comment]
Take a look at this log file.  Search for the time stamp 11:54:48.  You will see a lot more than just the ECONNRESET.  This happened at 12:25, 12:09, 11:54, 11:39, 11:09, 10:54.  At 11:09:27 it says 'Reboot Reason Received new state Software Reset CPU'.  Almost like it is resetting itself and when it boots back up it tells your software the door is open and then it figures out it is closed a few seconds later and says it is closed.  I think whatever is causing the reset is the key.


[homebridge-blaq.txt](https://github.com/user-attachments/files/16463840/homebridge-blaq.txt)

**Comment by JohnRucker** [comment]
I connected directly to my blaQ's web site and it has only been up for 10 minutes.  Your Plugin has been disable for hours so I don't think your code is causing the reset.  I wonder if you could test this by connecting to one of your blaQ's website and clicking on the restart button.   If that resets the unit I wonder if you will see your door open and close in Home Kit.

**Comment by KyleBoyer** [comment]
I just tried restarting the device via my GDO BlaQ website a few times, and I did not hit the same issue. I did not even see the eventsource error, according to the logs it just seemed to remain connected(?), but continued receiving eventsource messages as normal post-reboot.

I even tried to purposefully emit an error from the eventsource, and the auto reconnection happened, and I did not get open/closed events.

I did just release a new version a few minutes ago with additional logging around the target and current door states - can you please update to this version and re-capture the logs? The logs should now have debug level messages stating `returning {current/target} door state {state} because: {reason}`

I'm looking at the attached log file and I see some logs I'm not as familiar with - I'm wondering which of the following settings you enabled on the Konnected firmware settings:

Konnected Cloud
Local Native API
Local Web Page / API

I have all except Konnected Cloud, would it be possible to disable Konnected Cloud to see if that makes a difference?

Another thing - I have seen in some mention of [some hacky "heartbeat" logic when used for RATGDO, that prevents the device from resetting itself](https://github.com/BMDan/homebridge-ratgdo-esphome/blob/main/src/platformAccessory.ts#L220-L248). That logic just opens a connection, on an interval, to the Local Native API port for a period of time. I do have HomeAssistant running on my machine, so I'm also wondering if my HA instance is "already taking care of" this hacky heartbeat. If we don't get anywhere with the above attempts, I'm OK to add this hacky "heartbeat" logic into this plugin.

**Comment by KyleBoyer** [comment]
This is more info about that hacky "heartbeat" logic. Maybe this is the reason? If you observe the GDO BlaQ website logs, do you notice the uptime / restarts happening every 15min? I know I kinda asked this before, but before it was related to the open/close notices in HomeKit, now I'm wondering about the actual device resets.

https://esphome.io/components/api.html
<img width="697" alt="Screenshot 2024-08-01 at 10 10 03 PM" src="https://github.com/user-attachments/assets/a4989837-4d98-4abe-a9a0-140873956797">

**Comment by JohnRucker** [comment]
I just updated and got a two bogus open / closes right off the bat.  Here is the log, looks like some new info is in there.  According to the HomeKit activity log the open and closes occurred at 7:54am and 7:39am.

[homebridge-blaq.log-8.txt](https://github.com/user-attachments/files/16470695/homebridge-blaq.log-8.txt)

I don't see the heartbeat option in my blaq configuration.  Here is a screen shot of the config.
![image](https://github.com/user-attachments/assets/cc541017-e458-4ae9-85d7-976a8d2a4f44)
As for rebooting every 15 minutes it could be close to that.  I would say it is about every 10 to 20 minutes in that window it seems to reboot. 

I don't have Connected Cloud enabled, just Local Native API and Local Web Page / API.
![IMG_7127](https://github.com/user-attachments/assets/56ddd511-f37d-48cb-be6b-58f39c799749)

**Comment by KyleBoyer** [comment]
Hmm, I noticed an issue with the logging I added and have corrected it, can you please update to 0.2.27 and try to capture these events again?

Also in the attached log I see it mention captive portal - is that something you have enabled on this network? Could the captive portal be forcing the connection reset?

**Comment by JohnRucker** [comment]
Here you go.  Had a bogus event at 8:00, 8:11, 8:26.  I restarted the plugin around 8. It looked like it was getting a Bunch of errors.  I wonder if the captive portal has something to do with the web interface.  I made sure I didn't have any browsers open in the BlaQ web site.

[homebridge-blaq.log-10.txt](https://github.com/user-attachments/files/16480733/homebridge-blaq.log-10.txt)

**Comment by KyleBoyer** [comment]
Awesome, this log has some good info. It does appear like your BlaQ is restarting because "Software Reset CPU". After this happens, and the device boots, it reports the door state being open, and then two seconds later reports it being closed. I have a possible fix for this, that I can implement soon - it's a busy weekend for me, so I'll see if I can get to it this weekend. My proposed fix is to not update any state changes until the "synced" state is true.

**Comment by JohnRucker** [comment]
Hey bud get to it when and if you can. No worries on my side. Appreciate your time.

**Comment by KyleBoyer** [comment]
When you get a chance, can you try the latest version that I just released? I think that has the basics of the fix, but if it doesn't quite do it, I have some more tricks to implement.

**Comment by JohnRucker** [comment]
Downloaded it last night.  Not one false report!  Working like a champ!!  Thanks again for creating this plugin and the great support!!

**Comment by KyleBoyer** [comment]
Awesome news :) Not a problem, I'm happy to help! I did release 0.2.30 just a few minutes ago with a slight tweak/improvement to the logic - I now set `synced=false` whenever the eventsource reconnects, whereas before it would only reset the sync state when it got a sync event. This fixes the situation where the eventsource loses its connection, and the GDO BlaQ is not yet synced, and the GDO BlaQ outputs some state events before the synced state event like these ones(Motion/Obstruction/Motor/Wall Button):
<img width="841" alt="Screenshot 2024-08-04 at 8 51 57 AM" src="https://github.com/user-attachments/assets/e340e333-6490-4b87-ad7d-60a1e756881a">

**Comment by JohnRucker** [comment]
Sounds good.  I updated to 0.2.30 last night and all is good.  Thanks again.
